### PR TITLE
Release/v0.1.4

### PR DESCRIPTION
**Pull request by henhuy**
### Added
- Short link to Stemp-Tools on landing page
- Sphinx Makefile
- dynamic title for meta app lists

### Changed
- Removed unnecessary ionicon files
- Black style
- WAM installation instructions improved (esp. for Windows) #95
- Assumptions and sources are deleted if category is deleted (cascade)

### CODE REVIEW

**Review by nesnoj — APPROVED** [review]
There seem to be more changes you've done in Dec which have no entry in the changelog.
Please add them before you merge. Cheers

**Review by christian-rli — APPROVED** [review]
Looks okay. Maybe we can find a student to look at the travis errors :)

**Comment by henhuy** [comment]
Added entries in CHANGELOG.md

**Review by nesnoj — APPROVED** [review]
thx

**Pull request merged**
