### PR TITLE
Fixes/duplicate installed apps

### LINKED ISSUE #74: App settings interfere
If more than one app use the same settings variables, they conflict (last loaded app rules).

Current problem in FRED: https://github.com/rl-institut/WAM_APP_FRED/issues/49

Reason: The WAM reads the settings.py of each app which mays contain module config stuff like this one. So it's not a per-app config but a global (module) one.

This is a general WAM issue we have to solve!
Ideas, @henhuy ?

### PR DESCRIPTION
**Pull request by henhuy**
Every list entry from app-specific settings.py is checked for duplicates while importing into original wam.settings.
As before, additional packages can easily be added to wam.settings by:

```
# app/settings.py

INSTALLED_APPS = ['package']
```

### CODE REVIEW

**Review by nesnoj — CHANGES_REQUESTED** [review]
Hmm, when testing locally with current dev branches of ABW+FRED, I'm getting
```
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: leaflet
```
Have you tested this?

**Comment by henhuy** [comment]
This is because Fred app does not use my suggested solution for adding packages.
Instead it appends package to INSTALLED_APPS manually...
In this case, either Fred_app has to change to my suggestion, or has to avoid error itself.

**Comment by nesnoj** [comment]
> This is because Fred app does not use my suggested solution for adding packages.
> Instead it appends package to INSTALLED_APPS manually...
> In this case, either Fred_app has to change to my suggestion, or has to avoid error itself.

I request the FREDdies to use your suggestion @jh-RLI @christian-rli @Bachibouzouk

**Comment by nesnoj** [comment]
> ```
> django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: leaflet
> ```

Ok, this error vanished with https://github.com/rl-institut/WAM_APP_FRED/pull/52/commits/f6971a25d029cdc544a4071880ae6f82cc4fb1bd. But the coordinate problem persists.. @christian-rli

**Comment by nesnoj** [comment]
> Ok, this error vanished with [rl-institut/WAM_APP_FRED@f6971a2](https://github.com/rl-institut/WAM_APP_FRED/commit/f6971a25d029cdc544a4071880ae6f82cc4fb1bd). But the coordinate problem persists.. @christian-rli

Oh, I got the sense of this PR wrong, sorry. This belongs to #74

**Review by nesnoj — APPROVED** [review]

**Comment by nesnoj** [comment]
Pls merge

**Comment by Bachibouzouk** [comment]
> This is because Fred app does not use my suggested solution for adding packages.
> Instead it appends package to INSTALLED_APPS manually...
> In this case, either Fred_app has to change to my suggestion, or has to avoid error itself.

I agree that we should change FRED to the suggestion :)

This would be a good PR to also change the description of `app/settings.py` and `app/app_settings.py` to something less confusing and to add an explicit example of how to add packages to the app, without messing other apps, ie something like :

If your app requires the use of java packages, you should list them in the `settings.py` of your app (not the `settings.py` file form wam core) in the following way 
```
INSTALLED_APP = ['js_package']
```
Then, wam core will manage the packages' installation and avoid duplicate installations between the different apps.

**Comment by nesnoj** [comment]
> This would be a good PR to also change the description of `app/settings.py` and `app/app_settings.py`

Good point! Do you have time for this today? Unfortunately I don't :(

**Comment by Bachibouzouk** [comment]
> Good point! Do you have time for this today? Unfortunately I don't :(

I'll do that in the train and push the changes with my phone connection :)

**Comment by Bachibouzouk** [comment]
@nesnoj - you can merge now, I added the string in the doc :)

**Comment by Bachibouzouk** [comment]
@nesnoj - you can merge now, I added the string in the doc :)

**Comment by nesnoj** [comment]
> @nesnoj - you can merge now, I added the string in the doc :)

Thx!
The package conflict is not only js-related but a general problem, I adjusted the doc accordingly in 595acff74754e940b5509dcb629d8a527b40eaa2 ..

**Comment by nesnoj** [comment]
Also, I added a warning to docs to avoid package-specifix settings in 3821ca3b9b6ab201aea4faf7744645149210deda

**Pull request merged**
