### PR TITLE
Implemented SourceView with related models to show sources per app

### PR DESCRIPTION
**Pull request by henhuy**
Added new _meta_ app to store sources (and related categories) and assumptions. Sources and assumptions have attribute `app_name` to specifiy related app. View to show all sources for one app is implemented in meta.views.

**From SourceView docstring:**
Lists all sources grouped by source category

Sources can be filtered by app_name attribute. If base template is given
within specified app, SourceView extends this template. Otherwise, base
template from meta app is taken.

Usage:

    # in <my_app>/urls.py:

    from meta.models import SourceView

    urlpatterns = [
        ...
        path('sources/', SourcesView.as_view(app_name='<my_app>')),
        ...
    ]

### CODE REVIEW

**Comment by nesnoj** [comment]
Very nice work! :+1:
You also integrated the admin stuff, this allows me to hand this work over to someone else. Great!

I got some adjustments, but one question prior to my PR: What is value_type? the unit? (if not, I'll add the unit)

**Comment by henhuy** [comment]
Thanks.
> What is value_type?

I meant str/int/float - but maybe this isn't helpful. Adding a unit would instead, would be nice!

**Comment by nesnoj** [comment]
Ok I'll do so

**Comment by nesnoj** [comment]
Edit: As I think the assumptions are - at least in this first draft - for information purposes only, we do not need the type. I'll remove it.
If we want to allow for edits later on, We need a different concept here anyway.

**Comment by henhuy** [comment]
you are right!

**Comment by nesnoj** [comment]
Done.

Nice-to-have: Some metadata would be nice to get a better understanding of the columns, maybe a subset of RLI's v1.4 metadata standard. I'm also fine with just having it in the docsting or on a RTD page.

**Comment by henhuy** [comment]
Good idea! I also thought about using metadata standard directly. But for now, I don't have enough time to integrate it nicely...
I will open a new issue for that

**Pull request merged**
