### PR TITLE
Initial CI Travis setup

### LINKED ISSUE #23: There is no visible CI in place
We could (should?) setup CI for the WAM repository and begin to lint the code at first. Then we can slowly implement tests. 

I propose that we choose one of 
* https://travis-ci.org/
* https://circleci.com/ (I worked with this one so it might be more easy to setup)

@rl-institut/wam-team : let me know which one you prefer in the comments below :)

The easiest test to implement are on the `models`, but the `views` can also be tested: https://docs.djangoproject.com/en/2.1/intro/tutorial05/

### PR DESCRIPTION
**Pull request by Bachibouzouk**
Closes #23 

Hey @rl-institut/wam-team - Here is a first draft of a `travis.yml` configuration file. It is inspired from the [Travis CI documentation](https://docs.travis-ci.com/).

I also found some [real life example](https://github.com/getsentry/sentry/blob/master/.travis.yml) of  `travis.yml` file as well as an example of [conda use with Travis](https://gist.github.com/zshaheen/fe76d1507839ed6fbfbccef6b9c13ed9)

The first test I would like to setup are linting tests `flake8` (http://flake8.pycqa.org/en/latest/) and `pylint` (https://pylint.readthedocs.io/en/stable/), we can specify which rules we want to exclude from the tests if needbe :)

### CODE REVIEW

**Comment by Bachibouzouk** [comment]
@rl-institut/wam-team , thanks to @christian-rli Travis CI is setup on the repository !

To start I only applied the linter on the `wam` folder (it should only be valid on this branch as no other branch has a `.travis.yml` file (this file controls all the options of Travis on the repo)

The Check fail because the linters output errors, let me know if you can see them by clicking on the `details` link to the right of the tests. I propose we fix the linting error and merge this PR into master, then extend  test coverage to the rest of the repo via successive PRs.

**Comment by 4lm** [comment]
@Bachibouzouk, thank you! Yes, I can see the check details by clicking on details, and build log by further clicking on build! I support your suggestion to first make the linter happy and "extend test coverage to the rest of the repo via successive PRs." I'm really looking forward to this!

**Comment by christian-rli** [comment]
Thanks @Bachibouzouk for going ahead with this. I like the plan. Let's do it.

**Comment by nesnoj** [comment]
Thank you @Bachibouzouk!
Why do you use both `flake8` and `pylint`? Is it not sufficient to use only of them?

Another question we should discuss is: What's the minimum pylint score we want to achieve? (actually not [this](https://codegolf.stackexchange.com/questions/172445/get-the-lowest-possible-pylint-score-within-128-bytes-of-python) one ;)
According to [this source](http://www.academis.eu/posts/pylint), >7.0 seems to be good enough. Any suggestions/experiences?

**Comment by Bachibouzouk** [comment]
> Why do you use both `flake8` and `pylint`? Is it not sufficient to use only of them?

@nesnoj - `flake8` is more for PEP8 compatibility and `pylint` allow to also check imports and coding practices (there is the option of blocklisting variable names for example). In f000f40c590f149ef41345bb4d51bf439dcd5263, I added a `.pylintrc` template file for pylint options setup.

**Review by christian-rli — APPROVED** [review]
For my personal understanding: why move the line
from configobj import ConfigObj
to the bottom of imports?

**Comment by Bachibouzouk** [comment]
> Another question we should discuss is: What's the minimum pylint score we want to achieve? (actually not [this](https://codegolf.stackexchange.com/questions/172445/get-the-lowest-possible-pylint-score-within-128-bytes-of-python) one ;)

I think we have to get a score of 10/10 for the tests to pass, our degree of freedom here is more "which warning and error message do we want to disable so that all test pass". For example, the tests of this PR would not pass currently if the `missing-docstring` warning was not disabled (it requires a docstring for each modules as well, this is why I disabled it).

There is also the option of disabling specific warnings on a given line of a file or for a whole file.

**Comment by Bachibouzouk** [comment]
> For my personal understanding: why move the line
> from configobj import ConfigObj
> to the bottom of imports?

I guess that has to do with pylint enforcing 
1.  Standard library imports.
2.  Related third party imports.
3.  Local application/library specific imports.

from https://www.python.org/dev/peps/pep-0008/

**Pull request merged**
